services:
  - type: web
    name: zuri-mirror-chat
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: .output/public
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
